// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/ndaDayo/devdev/adapter/api/github"
	"github.com/ndaDayo/devdev/adapter/presenter/activity"
	"github.com/ndaDayo/devdev/domain/repository/activity"
	"github.com/ndaDayo/devdev/usecase/activity"
)

// Injectors from wire.go:

func InitializeActivityUseCase() *usecase.ActivityUseCase {
	codeActivityFetcher := github.NewCodeActivityFetcher()
	activityPresenter := presenter.NewActivityPresenter()
	activityUseCase := usecase.NewActivityUseCase(codeActivityFetcher, activityPresenter)
	return activityUseCase
}

// wire.go:

var activitySet = wire.NewSet(github.NewCodeActivityFetcher, wire.Bind(new(repository.Activity), new(*github.CodeActivityFetcher)), presenter.NewActivityPresenter, usecase.NewActivityUseCase)
